version: '3.8'
services:
  nextjs-app:
    build:
      context: frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-image:dev
    command: >
      sh -c "alembic upgrade head & uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - "8000:8000"
  db:
    image: postgres:12.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    expose:
      - 5432

volumes:
  db:
