"""empty message

Revision ID: 43a7af2cdb45
Revises: 85ccf768abea
Create Date: 2024-05-12 01:26:08.017494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a7af2cdb45'
down_revision: Union[str, None] = '85ccf768abea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('route_location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'route_location')
    # ### end Alembic commands ###
