"""initial

Revision ID: 80d1c8b46639
Revises: 
Create Date: 2024-05-11 13:46:16.516778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d1c8b46639'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed_actions', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('contact_phone_number', sa.String(), nullable=False),
    sa.Column('probably_dead', sa.Boolean(), nullable=False),
    sa.Column('is_soldier', sa.Boolean(), nullable=False),
    sa.Column('last_location_longitude', sa.Float(), nullable=False),
    sa.Column('last_location_latitude', sa.Float(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('regions')
    # ### end Alembic commands ###
