"""empty message

Revision ID: 85ccf768abea
Revises: 52f4dd8d845a
Create Date: 2024-05-11 23:43:42.425157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ccf768abea'
down_revision: Union[str, None] = '52f4dd8d845a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('contact_first_name', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('contact_last_name', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('contact_surname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'contact_surname')
    op.drop_column('requests', 'contact_last_name')
    op.drop_column('requests', 'contact_first_name')
    # ### end Alembic commands ###
