"""empty message

Revision ID: e34f0846e266
Revises: 43a7af2cdb45
Create Date: 2024-05-12 04:15:17.975486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34f0846e266'
down_revision: Union[str, None] = '43a7af2cdb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_places',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_places')
    # ### end Alembic commands ###
